import { useDeferredValue, useEffect, useMemo, useState, type FormEvent } from "react";
import { Activity, ArrowDown, ArrowDownRight, ArrowUpRight, Bell, Boxes, Check, ChevronDown, CircleHelp, ClipboardList, DollarSign, LayoutDashboard, ListFilter, MoreHorizontal, Package, Plus, Search, Settings2, ShoppingBag, SlidersHorizontal, Truck, X } from "lucide-react";

type Product={id:string;sku:string;name:string;category:string;stock:number;reorder:number;cost:number;location:string;initials:string;color:string};
type Order={id:string;customer:string;date:string;status:"Pending"|"Processing"|"Fulfilled";items:{productId:string;qty:number}[];total:number};
type Event={id:string;title:string;detail:string;when:string;kind:"in"|"out"|"order"};
const productsSeed:Product[]=[
 {id:"p1",sku:"CHR-1042",name:"Lounge Chair · Moss",category:"Furniture",stock:24,reorder:10,cost:289,location:"A-03-2",initials:"LC",color:"#6e8468"},
 {id:"p2",sku:"LMP-2208",name:"Arc Table Lamp",category:"Lighting",stock:7,reorder:12,cost:118,location:"B-02-1",initials:"TL",color:"#c29a5d"},
 {id:"p3",sku:"TXT-0184",name:"Woven Throw · Clay",category:"Textiles",stock:42,reorder:15,cost:64,location:"C-01-4",initials:"WT",color:"#b8745d"},
 {id:"p4",sku:"VSE-7731",name:"Studio Vase · Chalk",category:"Decor",stock:3,reorder:8,cost:38,location:"D-04-2",initials:"SV",color:"#9a8e7a"},
 {id:"p5",sku:"CHR-1027",name:"Dining Chair · Natural",category:"Furniture",stock:18,reorder:10,cost:176,location:"A-02-3",initials:"DC",color:"#98795d"},
 {id:"p6",sku:"LMP-2210",name:"Pendant Light · Linen",category:"Lighting",stock:0,reorder:6,cost:215,location:"B-01-3",initials:"PL",color:"#73869b"},
 {id:"p7",sku:"TXT-0211",name:"Linen Pillow Cover",category:"Textiles",stock:31,reorder:12,cost:32,location:"C-02-1",initials:"LP",color:"#8b9a87"},
 {id:"p8",sku:"DEC-0043",name:"Stoneware Tray",category:"Decor",stock:16,reorder:8,cost:52,location:"D-01-1",initials:"ST",color:"#aa8e74"},
];
const ordersSeed:Order[]=[{id:"SO-10842",customer:"Atelier House",date:"Today, 10:14 AM",status:"Pending",items:[{productId:"p1",qty:2},{productId:"p3",qty:1}],total:642},{id:"SO-10841",customer:"June & Co.",date:"Today, 9:52 AM",status:"Processing",items:[{productId:"p2",qty:2}],total:278},{id:"SO-10840",customer:"Morrow Living",date:"Today, 9:20 AM",status:"Pending",items:[{productId:"p5",qty:4},{productId:"p7",qty:4}],total:832},{id:"SO-10839",customer:"Hearth Studio",date:"Yesterday, 4:32 PM",status:"Fulfilled",items:[{productId:"p4",qty:3}],total:171}];
const eventSeed:Event[]=[{id:"e1",title:"Stock received",detail:"Lounge Chair · Moss · +12 units",when:"Today · 9:40 AM",kind:"in"},{id:"e2",title:"Order placed",detail:"SO-10842 · Atelier House",when:"Today · 10:14 AM",kind:"order"},{id:"e3",title:"Stock adjusted",detail:"Studio Vase · Chalk · −2 units",when:"Today · 8:56 AM",kind:"out"}];
const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n);
const stockStatus=(p:Product)=>p.stock===0?"Out of stock":p.stock<=p.reorder?"Low stock":"In stock";

export default function App(){
 const [products,setProducts]=useState(productsSeed),[orders,setOrders]=useState(ordersSeed),[events,setEvents]=useState(eventSeed),[view,setView]=useState<"Inventory"|"Orders"|"Activity">("Inventory"),[category,setCategory]=useState("All products"),[search,setSearch]=useState(""),[modal,setModal]=useState(false),[draft,setDraft]=useState({name:"",sku:"",category:"Furniture",stock:"",reorder:""}),[ready,setReady]=useState(false),[notice,setNotice]=useState("");
 const deferredSearch=useDeferredValue(search);
 useEffect(()=>{try{const saved=localStorage.getItem("stockroom-state");if(saved){const d=JSON.parse(saved);if(d.products)setProducts(d.products);if(d.orders)setOrders(d.orders);if(d.events)setEvents(d.events);}}catch{}setReady(true);},[]);
 useEffect(()=>{if(ready)localStorage.setItem("stockroom-state",JSON.stringify({products,orders,events}));},[products,orders,events,ready]);
 const filtered=useMemo(()=>products.filter(p=>(category==="All products"||p.category===category)&&`${p.name} ${p.sku} ${p.location}`.toLowerCase().includes(deferredSearch.toLowerCase())),[products,category,deferredSearch]);
 const low=products.filter(p=>p.stock>0&&p.stock<=p.reorder),out=products.filter(p=>p.stock===0),openOrders=orders.filter(o=>o.status!=="Fulfilled");
 const notify=(s:string)=>{setNotice(s);window.setTimeout(()=>setNotice(""),2600)};
 const log=(title:string,detail:string,kind:Event["kind"])=>setEvents([{id:crypto.randomUUID(),title,detail,when:"Just now",kind},...events]);
 const adjust=(p:Product,delta:number)=>{if(p.stock+delta<0)return;setProducts(products.map(x=>x.id===p.id?{...x,stock:x.stock+delta}:x));log(delta>0?"Stock received":"Stock adjusted",`${p.name} · ${delta>0?"+":""}${delta} units`,delta>0?"in":"out");notify(`${p.name}: stock ${delta>0?"increased":"adjusted"}.`);};
 const addProduct=(e:FormEvent)=>{e.preventDefault();const stock=Number(draft.stock),reorder=Number(draft.reorder);if(!draft.name.trim()||!draft.sku.trim()||!Number.isFinite(stock)||stock<0||!Number.isFinite(reorder)||reorder<0)return;const p:Product={id:crypto.randomUUID(),name:draft.name.trim(),sku:draft.sku.trim().toUpperCase(),category:draft.category,stock,reorder,cost:0,location:"Unassigned",initials:draft.name.trim().split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase(),color:"#5d806a"};setProducts([p,...products]);log("Product added",`${p.name} · ${p.stock} units`,"in");setDraft({name:"",sku:"",category:"Furniture",stock:"",reorder:""});setModal(false);notify("Product added to inventory.");};
 const fulfill=(order:Order)=>{const needs=order.items.map(i=>({item:i,product:products.find(p=>p.id===i.productId)}));const missing=needs.find(x=>!x.product||x.product.stock<x.item.qty);if(missing){notify(`Not enough stock for ${missing.product?.name??"an order item"}.`);return;}setProducts(products.map(p=>{const i=order.items.find(x=>x.productId===p.id);return i?{...p,stock:p.stock-i.qty}:p;}));setOrders(orders.map(o=>o.id===order.id?{...o,status:"Fulfilled"}:o));log("Order fulfilled",`${order.id} · ${order.customer}`,"order");notify(`${order.id} fulfilled and inventory updated.`);};
 const totalUnits=products.reduce((n,p)=>n+p.stock,0),inventoryValue=products.reduce((n,p)=>n+p.stock*p.cost,0);
 return <div className="stockroom">
  <aside className="sidebar"><a className="brand" href="#"><span className="brand-icon"><Boxes size={18}/></span><span>stockroom<small>OPERATIONS</small></span></a><button className="warehouse"><span className="warehouse-mark">N</span><span><b>Northstar Home</b><small>Primary warehouse</small></span><ChevronDown size={14}/></button><span className="section-label">WORKSPACE</span><nav className="main-nav">{([ ["Overview",LayoutDashboard],["Inventory",Package],["Orders",ShoppingBag],["Activity",Activity] ] as const).map(([label,Icon])=><button key={label} className={`nav-link ${view===label?"active":""}`} onClick={()=>label==="Overview"?setView("Inventory"):setView(label as "Inventory"|"Orders"|"Activity")}><Icon size={17}/>{label}{label==="Orders"&&<small>{openOrders.length}</small>}</button>)}</nav><div className="sidebar-spacer"/><div className="reorder-card"><div><span>RESTOCK WATCH</span><span className="watch-dot"/></div><b>{low.length+out.length} items need attention</b><p>{out.length?`${out.length} out of stock`:`${low.length} approaching reorder point`}</p><button onClick={()=>{setCategory("All products");setView("Inventory");}}>Review stock <ArrowDownRight size={14}/></button></div><button className="nav-link lower"><CircleHelp size={16}/>Help & support</button><button className="nav-link lower"><Settings2 size={16}/>Settings</button><div className="operator"><div className="operator-avatar">SJ</div><div><b>Saurabh Jaju</b><small>Warehouse admin</small></div><MoreHorizontal size={16}/></div></aside>
  <main className="main"><header className="topbar"><div className="crumbs">Northstar Home <span>/</span> <b>{view}</b></div><div className="top-right"><span className="sync-state"><i/> All changes saved</span><button className="top-icon" aria-label="Notifications"><Bell size={17}/><i/></button><div className="top-avatar">SJ</div></div></header>
   <div className="page"><div className="page-title"><div><div className="eyebrow">TUESDAY, OCTOBER 1, 2026 <span>·</span> PRIMARY WAREHOUSE</div><h1>{view=== "Inventory"?"Inventory overview":view==="Orders"?"Order fulfillment":"Stock activity"}</h1><p>{view==="Inventory"?"A steady view of what’s in stock and what needs a closer look.":view==="Orders"?"Keep each order moving from received to ready to ship.":"Every movement, received and recorded."}</p></div><button className="add-button" onClick={()=>setModal(true)}><Plus size={16}/> Add product</button></div>
    <div className="metrics"><article><div className="metric-label">INVENTORY VALUE <span className="metric-icon green"><DollarSign size={15}/></span></div><b>{money(inventoryValue)}</b><small><ArrowUpRight size={13}/> 8.2% <span>compared to last month</span></small></article><article><div className="metric-label">TOTAL UNITS <span className="metric-icon blue"><Boxes size={15}/></span></div><b>{totalUnits.toLocaleString()}</b><small><span>{products.length} products</span><span>across 4 categories</span></small></article><article className={low.length+out.length?"attention":""}><div className="metric-label">RESTOCK NEEDED <span className="metric-icon amber"><ListFilter size={15}/></span></div><b>{String(low.length+out.length).padStart(2,"0")}</b><small><span>{out.length} out of stock</span><span>·</span><span>{low.length} running low</span></small></article><article><div className="metric-label">OPEN ORDERS <span className="metric-icon violet"><ClipboardList size={15}/></span></div><b>{String(openOrders.length).padStart(2,"0")}</b><small><Truck size={13}/><span>{orders.filter(o=>o.status==="Pending").length} waiting to be picked</span></small></article></div>
    <div className="content-heading"><div><div className="eyebrow">OPERATIONS</div><h2>{view=== "Inventory"?"Stock on hand":view==="Orders"?"Recent orders":"Activity log"} <span>{view==="Inventory"?products.length:view==="Orders"?orders.length:events.length}</span></h2></div>{view==="Inventory"&&<button className="quiet-button"><SlidersHorizontal size={15}/> Customize view</button>}</div>
    <div className="toolbar"><div className="tabs">{view==="Inventory"?["All products","Furniture","Lighting","Textiles","Decor"].map(c=><button key={c} className={category===c?"active":""} onClick={()=>setCategory(c)}>{c}{c==="All products"&&<span>{products.length}</span>}</button>):<span className="toolbar-copy">{view==="Orders"?"Order queue · updated just now":"Latest movement first"}</span>}</div><div className="table-tools"><label className="search"><Search size={14}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={view==="Inventory"?"Search products…":"Search orders…"}/></label><button className="filter-button"><ListFilter size={14}/> Filter</button><button className="view-menu"><MoreHorizontal size={16}/></button></div></div>
    {view==="Inventory"&&<div className="table-wrap"><table><thead><tr><th>PRODUCT</th><th>SKU</th><th>CATEGORY</th><th>STOCK ON HAND</th><th>STATUS</th><th>UNIT COST</th><th>LOCATION</th><th/></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td><div className="product"><span className="product-thumb" style={{background:p.color}}>{p.initials}</span><span><b>{p.name}</b><small>{p.category}</small></span></div></td><td className="sku">{p.sku}</td><td><span className="category-chip">{p.category}</span></td><td><div className="stock-value"><b>{p.stock}</b><span>/ {p.reorder} min</span><div className="stock-adjust"><button onClick={()=>adjust(p,-1)} aria-label={`Remove one ${p.name} from stock`} disabled={p.stock===0}>−</button><button onClick={()=>adjust(p,1)} aria-label={`Add one ${p.name} to stock`}>+</button></div></div></td><td><span className={`stock-badge ${stockStatus(p).toLowerCase().replaceAll(" ","-")}`}><i/>{stockStatus(p)}</span></td><td className="cost">{p.cost?money(p.cost):"—"}</td><td className="location">{p.location}</td><td><button className="row-menu" aria-label={`More actions for ${p.name}`}><MoreHorizontal size={16}/></button></td></tr>)}{filtered.length===0&&<tr><td colSpan={8} className="empty">No products match your search.</td></tr>}</tbody></table></div>}
    {view==="Orders"&&<div className="orders-list">{orders.filter(o=>`${o.id} ${o.customer}`.toLowerCase().includes(deferredSearch.toLowerCase())).map(o=><article className="order-card" key={o.id}><div className="order-icon"><ShoppingBag size={16}/></div><div className="order-main"><div><b>{o.id}</b><span className={`order-status ${o.status.toLowerCase()}`}><i/>{o.status}</span></div><small>{o.customer} <span>·</span> {o.date}</small><p>{o.items.map(i=>`${products.find(p=>p.id===i.productId)?.name??"Item"} × ${i.qty}`).join("  ·  ")}</p></div><div className="order-total"><span>ORDER TOTAL</span><b>{money(o.total)}</b></div>{o.status!=="Fulfilled"?<button className="fulfill-button" onClick={()=>fulfill(o)}><Check size={14}/> Fulfill order</button>:<span className="fulfilled-check"><Check size={15}/> Fulfilled</span>}</article>)}</div>}
    {view==="Activity"&&<div className="activity-list">{events.map(ev=><article key={ev.id}><span className={`activity-icon ${ev.kind}`}>{ev.kind==="in"?<ArrowDownRight size={16}/>:ev.kind==="out"?<ArrowUpRight size={16}/>:<ShoppingBag size={15}/>}</span><div><b>{ev.title}</b><p>{ev.detail}</p></div><time>{ev.when}</time></article>)}</div>}
    <div className="bottom-note"><span className="note-icon"><Check size={13}/></span><span><b>Stock is looking steady.</b> Every adjustment is captured in your activity log.</span><button onClick={()=>setView("Activity")}>View activity <ArrowUpRight size={13}/></button></div><footer className="page-footer"><span>STOCKROOM · OPERATIONS WORKSPACE</span><span>DEMO DATA · SAVED IN THIS BROWSER</span></footer>
   </div>
  </main>
  {notice&&<div className="toast" role="status"><Check size={15}/>{notice}<button onClick={()=>setNotice("")} aria-label="Dismiss message"><X size={14}/></button></div>}
  {modal&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setModal(false)}}><form className="modal" onSubmit={addProduct}><button type="button" className="modal-close" onClick={()=>setModal(false)} aria-label="Close"><X size={17}/></button><span className="modal-icon"><Package size={18}/></span><div className="eyebrow">CATALOG</div><h2>Add a product</h2><p>Give the team a clear starting point for this item.</p><label>Product name<input autoFocus required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="e.g. Oak Side Table"/></label><div className="form-row"><label>SKU<input required value={draft.sku} onChange={e=>setDraft({...draft,sku:e.target.value})} placeholder="e.g. FUR-106"/></label><label>Category<select value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}>{["Furniture","Lighting","Textiles","Decor"].map(c=><option key={c}>{c}</option>)}</select></label></div><div className="form-row"><label>Starting stock<input type="number" min="0" required value={draft.stock} onChange={e=>setDraft({...draft,stock:e.target.value})} placeholder="0"/></label><label>Reorder point<input type="number" min="0" required value={draft.reorder} onChange={e=>setDraft({...draft,reorder:e.target.value})} placeholder="10"/></label></div><div className="modal-actions"><button type="button" className="cancel" onClick={()=>setModal(false)}>Cancel</button><button className="add-button" type="submit"><Plus size={15}/> Add to inventory</button></div></form></div>}
 </div>;
}

